name: Test Action Locally
on: 
  push:
    branches:
      - dev

jobs:
  test_suite:
    runs-on: ${{ matrix.os }}
    name: Test - ${{ matrix.os }} - Node ${{ matrix.node }}
    timeout-minutes: 30
    strategy:
      matrix:
        node: [14]
        #os: [ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node }}
      - name: Install Deps
        run: |
          npm ci
      - name: Run Build
        run: npm run build
      - name: Run it
        uses: ./
        with:
          github-secret: ${{ secrets.github_token }}
          gist-id: 'test_gist_id'
          dry-run: true
